/**
 * Copies the ABIs the frontend actually calls into src/web3/abis.js.
 * Run after any contract change: npm run export-abis
 */
const fs = require('fs');
const path = require('path');

const WANTED = ['MixTape', 'TapesToken', 'Jukebox'];
const artifacts = path.join(__dirname, '..', 'artifacts', 'contracts');
const out = path.join(__dirname, '..', '..', 'src', 'web3', 'abis.js');

const abis = {};
for (const name of WANTED) {
  const file = path.join(artifacts, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(file)) throw new Error(`Missing artifact for ${name} — run "npm run build" first`);
  // Events and functions only; the frontend has no use for the rest.
  abis[name] = JSON.parse(fs.readFileSync(file, 'utf8')).abi;
}

const banner = `// Generated by contracts/scripts/export-abis.js — do not edit by hand.\n`
  + `// Regenerate with: cd contracts && npm run export-abis\n\n`;

const body = Object.entries(abis)
  .map(([name, abi]) => `export const ${name.toLowerCase()}Abi = ${JSON.stringify(abi, null, 2)};`)
  .join('\n\n');

fs.writeFileSync(out, banner + body + '\n');
console.log(`Wrote ${out}`);
for (const [n, a] of Object.entries(abis)) console.log(`  ${n}: ${a.length} entries`);
